# Generated by Django 3.1.5 on 2021-03-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0004_auto_20210306_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_favorite',
        ),
        migrations.AlterField(
            model_name='event',
            name='detail',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Conferences', 'Conferences'), ('Workshops and classes', 'Workshops and classes'), ('Awards and competitions', 'Awards and competitions'), ('Festivals and parties', 'Festivals and parties'), ('Birthday', 'Birthday')], max_length=100),
        ),
    ]
